// <auto-generated />
namespace ARS.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DBImprovement : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DBImprovement));
        
        string IMigrationMetadata.Id
        {
            get { return "202008011414353_DB-Improvement"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
